### ISSUE TITLE
Bug: additional capital of the emoji

### ISSUE THREAD

**Issue by hiberabyss** [crimx/hexo-filter-github-emojis#9]
After install this plugin, and input `:sparkles:` in my blog. There will be capital with emoji like following image:

![image](https://user-images.githubusercontent.com/2898670/33322872-a5c554b6-d485-11e7-87af-7851cf842261.png)

My configurations:

```
githubEmojis:
  enable: true
  className: github-emoji
  unicode: false
  styles:
    display: inline
    vertical-align: bottom
  localEmojis:
```
